// ── Types ──────────────────────────────────────────────────────────────────

import type {
  Course,
  CourseType,
  EnrolledCourse,
  Category,
  OrgAnnouncement,
  UserStats,
} from "@/lib/models";
export type {
  Course,
  CourseType,
  EnrolledCourse,
  Category,
  OrgAnnouncement,
  UserStats,
} from "@/lib/models";

// ── Hero ───────────────────────────────────────────────────────────────────

export const heroCourse: EnrolledCourse = {
  id: "hero-1",
  title: "안전보건관리체계와 10대 필수 안전수칙 이해",
  instructor: "김현수",
  category: "safety-mgmt",
  categoryLabel: "안전관리",
  thumbnail: "linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)",
  accentColor: "#34d399",
  rating: 4.9,
  reviewCount: 2184,
  duration: "24시간 30분",
  level: "중급",
  tags: ["안전보건관리", "법규", "현장적용"],
  price: 89000,
  isNew: false,
  isBestseller: true,
  type: "online",
  progress: 34,
  lastAccessedAt: "2026-03-11",
  nextLessonTitle: "7-3. 안전보건관리체계 구축 실전 사례",
};

// ── In-progress courses ────────────────────────────────────────────────────

export const inProgressCourses: EnrolledCourse[] = [
  { ...heroCourse, sessionId: "ss-1" },
  {
    id: "ip-2",
    title: "핵심안전수칙 이해",
    instructor: "이정민",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #134e5e, #71b280)",
    accentColor: "#4ade80",
    rating: 4.8,
    reviewCount: 1850,
    duration: "18시간",
    level: "초급",
    tags: ["안전수칙", "현장안전", "사고예방"],
    price: 59000,
    isNew: true,
    isBestseller: false,
    type: "online",
    progress: 67,
    lastAccessedAt: "2026-03-09",
    nextLessonTitle: "5-2. 위험 유형별 핵심 수칙 적용",
    sessionId: "ss-2",
  },
  {
    id: "ip-3",
    title: "위험관리실무",
    instructor: "박성훈",
    category: "risk-mgmt",
    categoryLabel: "리스크관리",
    thumbnail: "linear-gradient(135deg, #1a0040, #4a1090)",
    accentColor: "#a78bfa",
    rating: 4.7,
    reviewCount: 980,
    duration: "20시간",
    level: "중급",
    tags: ["위험성평가", "리스크", "재해통계"],
    price: 79000,
    isNew: false,
    isBestseller: true,
    type: "offline",
    progress: 12,
    lastAccessedAt: "2026-03-05",
    nextLessonTitle: "3-1. 위험성 평가 절차 이해",
    sessionId: "ss-3",
  },
];

// ── Recommended courses ────────────────────────────────────────────────────

export const recommendedCourses: Course[] = [
  {
    id: "r-1",
    title: "안전문화 주도 및 경영 역량",
    instructor: "김현수",
    category: "safety-culture",
    categoryLabel: "안전문화",
    thumbnail: "linear-gradient(135deg, #1a1a2e, #16213e)",
    accentColor: "#818cf8",
    rating: 4.9,
    reviewCount: 1640,
    duration: "30시간",
    level: "고급",
    tags: ["안전문화", "경영역량", "리더십"],
    price: 120000,
    isNew: true,
    isBestseller: true,
    type: "online",
  },
  {
    id: "r-2",
    title: "재해 통계 분석",
    instructor: "박성훈",
    category: "risk-mgmt",
    categoryLabel: "리스크관리",
    thumbnail: "linear-gradient(135deg, #0d1117, #21262d)",
    accentColor: "#60a5fa",
    rating: 4.7,
    reviewCount: 720,
    duration: "16시간",
    level: "중급",
    tags: ["재해통계", "데이터분석", "안전지표"],
    price: 65000,
    isNew: false,
    isBestseller: false,
    type: "online",
  },
  {
    id: "r-3",
    title: "안전마인드 향상",
    instructor: "이정민",
    category: "safety-culture",
    categoryLabel: "안전문화",
    thumbnail: "linear-gradient(135deg, #134e5e, #2d7a4f)",
    accentColor: "#4ade80",
    rating: 4.8,
    reviewCount: 2100,
    duration: "12시간",
    level: "초급",
    tags: ["안전마인드", "의식개선", "행동변화"],
    price: 0,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "r-4",
    title: "법규해석 및 이해",
    instructor: "김현수",
    category: "regulation",
    categoryLabel: "법규·규정",
    thumbnail: "linear-gradient(135deg, #1e3a5f, #2563eb)",
    accentColor: "#818cf8",
    rating: 4.8,
    reviewCount: 1120,
    duration: "22시간",
    level: "중급",
    tags: ["산업안전보건법", "중대재해", "법규"],
    price: 85000,
    isNew: false,
    isBestseller: false,
    type: "online",
  },
  {
    id: "r-5",
    title: "핵심 리스크 통제 역량",
    instructor: "박성훈",
    category: "risk-mgmt",
    categoryLabel: "리스크관리",
    thumbnail: "linear-gradient(135deg, #1c1c1e, #3a3a3c)",
    accentColor: "#fb923c",
    rating: 4.6,
    reviewCount: 560,
    duration: "26시간",
    level: "중급",
    tags: ["리스크통제", "위험성평가", "예방"],
    price: 95000,
    isNew: true,
    isBestseller: false,
    type: "online",
  },
  {
    id: "r-6",
    title: "안전관리 실무 역량",
    instructor: "이정민",
    category: "safety-mgmt",
    categoryLabel: "안전관리",
    thumbnail: "linear-gradient(135deg, #1a3a2a, #2d7a4f)",
    accentColor: "#4ade80",
    rating: 4.7,
    reviewCount: 1380,
    duration: "28시간",
    level: "중급",
    tags: ["안전관리", "실무", "현장적용"],
    price: 89000,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "r-7",
    title: "사고 예방 기본 역량",
    instructor: "이정민",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #1e3a5f, #2563eb)",
    accentColor: "#38bdf8",
    rating: 4.8,
    reviewCount: 2400,
    duration: "14시간",
    level: "입문",
    tags: ["사고예방", "안전기초", "현장"],
    price: 0,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "r-8",
    title: "안전 행동 관찰",
    instructor: "이정민",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #1a0a00, #c75000)",
    accentColor: "#fb923c",
    rating: 4.9,
    reviewCount: 890,
    duration: "18시간",
    level: "초급",
    tags: ["행동관찰", "BBS", "안전문화"],
    price: 69000,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "r-9",
    title: "현장 안전 집중 부트캠프 (오프라인)",
    instructor: "이정민",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #1a0040, #4a1090)",
    accentColor: "#a78bfa",
    rating: 4.9,
    reviewCount: 210,
    duration: "4주 · 주 2회",
    level: "초급",
    tags: ["현장안전", "실습", "오프라인"],
    price: 680000,
    isNew: true,
    isBestseller: false,
    type: "offline",
    location: "서울 강남구 테헤란로 152",
    nextSessionDate: "2026-04-07",
    capacity: 20,
    enrolledCount: 14,
  },
  {
    id: "r-10",
    title: "안전보건관리 심화 (블렌디드)",
    instructor: "김현수",
    category: "safety-mgmt",
    categoryLabel: "안전관리",
    thumbnail: "linear-gradient(135deg, #0a1628, #1e3a6e)",
    accentColor: "#60a5fa",
    rating: 4.8,
    reviewCount: 145,
    duration: "6주 (온라인 + 월 1회 오프라인)",
    level: "고급",
    tags: ["안전보건관리", "블렌디드", "심화"],
    price: 390000,
    isNew: false,
    isBestseller: false,
    type: "blended",
    location: "서울 마포구 공덕동",
    nextSessionDate: "2026-04-12",
    capacity: 30,
    enrolledCount: 22,
  },
];

// ── Popular courses ────────────────────────────────────────────────────────

export const popularCourses: Course[] = [
  {
    id: "p-1",
    title: "중대재해처벌법 완전 이해",
    instructor: "김현수",
    category: "regulation",
    categoryLabel: "법규·규정",
    thumbnail: "linear-gradient(135deg, #064e3b, #065f46)",
    accentColor: "#34d399",
    rating: 4.9,
    reviewCount: 3800,
    duration: "10시간",
    level: "초급",
    tags: ["중대재해법", "법규", "의무사항"],
    price: 49000,
    isNew: true,
    isBestseller: true,
    type: "online",
  },
  {
    id: "p-2",
    title: "비상대응 및 대피 절차",
    instructor: "이정민",
    category: "emergency",
    categoryLabel: "비상대응",
    thumbnail: "linear-gradient(135deg, #7f1d1d, #b91c1c)",
    accentColor: "#f87171",
    rating: 4.7,
    reviewCount: 1150,
    duration: "16시간",
    level: "초급",
    tags: ["비상대응", "대피", "응급처치"],
    price: 55000,
    isNew: false,
    isBestseller: false,
    type: "online",
  },
  {
    id: "p-3",
    title: "화학물질 취급 안전",
    instructor: "박성훈",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #18181b, #3f3f46)",
    accentColor: "#a1a1aa",
    rating: 4.6,
    reviewCount: 870,
    duration: "14시간",
    level: "초급",
    tags: ["화학물질", "MSDS", "보호구"],
    price: 59000,
    isNew: false,
    isBestseller: false,
    type: "online",
  },
  {
    id: "p-4",
    title: "건설 현장 안전 실무",
    instructor: "이정민",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #1a0000, #7f1d1d)",
    accentColor: "#f87171",
    rating: 4.8,
    reviewCount: 1420,
    duration: "30시간",
    level: "중급",
    tags: ["건설안전", "추락방지", "현장"],
    price: 99000,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "p-5",
    title: "보호구 착용 및 관리",
    instructor: "이정민",
    category: "field-safety",
    categoryLabel: "현장안전",
    thumbnail: "linear-gradient(135deg, #1a0030, #6b21a8)",
    accentColor: "#c084fc",
    rating: 4.7,
    reviewCount: 990,
    duration: "8시간",
    level: "입문",
    tags: ["보호구", "PPE", "착용법"],
    price: 0,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "p-6",
    title: "안전점검 체크리스트 실무",
    instructor: "박성훈",
    category: "safety-mgmt",
    categoryLabel: "안전관리",
    thumbnail: "linear-gradient(135deg, #14532d, #16a34a)",
    accentColor: "#4ade80",
    rating: 4.8,
    reviewCount: 1960,
    duration: "10시간",
    level: "초급",
    tags: ["안전점검", "체크리스트", "관리"],
    price: 39000,
    isNew: false,
    isBestseller: true,
    type: "online",
  },
  {
    id: "p-7",
    title: "안전보건 관리자 양성 과정 (오프라인 집중반)",
    instructor: "김현수",
    category: "safety-mgmt",
    categoryLabel: "안전관리",
    thumbnail: "linear-gradient(135deg, #0c1445, #1e3799)",
    accentColor: "#818cf8",
    rating: 4.8,
    reviewCount: 88,
    duration: "2일 (16h)",
    level: "중급",
    tags: ["관리자양성", "실습", "오프라인"],
    price: 220000,
    isNew: true,
    isBestseller: false,
    type: "offline",
    location: "부산 해운대구 센텀시티로",
    nextSessionDate: "2026-04-19",
    capacity: 25,
    enrolledCount: 18,
  },
];

// ── Categories ─────────────────────────────────────────────────────────────

export const categories: Category[] = [
  { id: "all",           label: "전체" },
  { id: "safety-mgmt",  label: "안전관리" },
  { id: "regulation",   label: "법규·규정" },
  { id: "risk-mgmt",    label: "리스크관리" },
  { id: "safety-culture", label: "안전문화" },
  { id: "emergency",    label: "비상대응" },
  { id: "field-safety", label: "현장안전" },
];

// ── Courses by category ────────────────────────────────────────────────────

export const allCourses: Course[] = [...recommendedCourses, ...popularCourses];

export const courseById: Record<string, Course> = Object.fromEntries(
  allCourses.map((c) => [c.id, c])
);

export const coursesByCategory: Record<string, Course[]> = {
  all:            allCourses,
  "safety-mgmt":  allCourses.filter((c) => c.category === "safety-mgmt"),
  "regulation":   allCourses.filter((c) => c.category === "regulation"),
  "risk-mgmt":    allCourses.filter((c) => c.category === "risk-mgmt"),
  "safety-culture": allCourses.filter((c) => c.category === "safety-culture"),
  "emergency":    allCourses.filter((c) => c.category === "emergency"),
  "field-safety": allCourses.filter((c) => c.category === "field-safety"),
};

// ── User stats ─────────────────────────────────────────────────────────────

export const userStats: UserStats = {
  completedCourses: 12,
  inProgressCourses: 3,
  totalLearningMinutes: 3240,
  certificates: 8,
};

// ── 필수 수강 과정 (B2B mandatoryCourses) ──────────────────────────────────

export const requiredCourses: Course[] = allCourses.filter((c) => c.isRequired);

// ── 내 부서 대상 과정 (B2B orgStructure) — 현장관리팀 mock ──────────────────
// 실제 구현에서는 서버가 learner.orgTeamId 기준으로 필터링한 결과를 반환.
// 여기서는 현장관리팀(team-field) 대상으로 지정된 과정을 수동 큐레이션.
export const deptTargetedCourses: Course[] = [
  allCourses.find((c) => c.id === "hero-1")!,
  allCourses.find((c) => c.id === "r-1")!,
  allCourses.find((c) => c.id === "r-4")!,
  allCourses.find((c) => c.id === "r-6")!,
].filter(Boolean);

// ── Announcements ──────────────────────────────────────────────────────────

export const announcements: OrgAnnouncement[] = [
  { id: "a1", tenantId: "t-b2c", subtype: "이벤트",   title: "봄 안전교육 특별 할인 — 4/30까지",                      targetType: "ALL_MEMBERS", status: "PUBLISHED", sentAt: "2026-03-10", views: 0, createdAt: "2026-03-10T00:00:00Z" },
  { id: "a2", tenantId: "t-b2c", subtype: "공지",     title: "수료증 발급 시스템 개선 안내",                           targetType: "ALL_MEMBERS", status: "PUBLISHED", sentAt: "2026-03-08", views: 0, createdAt: "2026-03-08T00:00:00Z" },
  { id: "a3", tenantId: "t-b2c", subtype: "업데이트", title: "모바일 앱 v3.2 업데이트 — 오프라인 재생 지원",           targetType: "ALL_MEMBERS", status: "PUBLISHED", sentAt: "2026-03-05", views: 0, createdAt: "2026-03-05T00:00:00Z" },
  { id: "a4", tenantId: "t-b2c", subtype: "공지",     title: "[필독] 개인정보 처리방침 개정 안내",                     targetType: "ALL_MEMBERS", status: "PUBLISHED", sentAt: "2026-02-28", views: 0, createdAt: "2026-02-28T00:00:00Z" },
  { id: "a5", tenantId: "t-b2c", subtype: "이벤트",   title: "친구 초대 이벤트 — 안전교육 수강권 증정",               targetType: "ALL_MEMBERS", status: "PUBLISHED", sentAt: "2026-02-20", views: 0, createdAt: "2026-02-20T00:00:00Z" },
  { id: "a6", tenantId: "t-b2c", subtype: "공지",     title: "연휴 기간 CS 운영 시간 안내",                           targetType: "ALL_MEMBERS", status: "PUBLISHED", sentAt: "2026-01-25", views: 0, createdAt: "2026-01-25T00:00:00Z" },
];
