import type { Announcement } from "@/lib/models";

export const ANNOUNCEMENTS: Announcement[] = [
  {
    id: "ann-001",
    scope: "PLATFORM",
    subtype: "MAINTENANCE",
    title: "[점검 예고] 3월 25일(화) 새벽 2~5시 정기 점검",
    content: "데이터베이스 버전 업그레이드 및 인프라 안정화 작업으로 인해 서비스가 일시 중단됩니다.\n\n• 점검 일시: 2026년 3월 25일(화) 02:00 ~ 05:00\n• 영향 범위: 전체 테넌트 서비스 접속 불가\n• 학습 진행 데이터는 점검 시작 전 자동 저장됩니다.\n\n불편을 드려 죄송합니다.",
    targetType: "ALL_TENANTS",
    status: "SCHEDULED",
    scheduledAt: "2026-03-24T10:00:00Z",
    views: 0,
    createdAt: "2026-03-18T09:00:00Z",
    createdBy: "ops@open-knock.com",
  },
  {
    id: "ann-002",
    scope: "PLATFORM",
    subtype: "UPDATE",
    title: "[업데이트] 강의 플레이어 v2.4 배포 — 북마크·구간 반복 기능 추가",
    content: "3월 15일부로 강의 플레이어가 v2.4로 업데이트되었습니다.\n\n주요 변경 사항:\n• 북마크 기능: 원하는 구간에 메모와 함께 북마크 저장\n• 구간 반복 재생: A-B 구간 반복 설정\n• 재생 속도 0.5x ~ 3.0x 지원\n• 자막 배경 색상 커스터마이징\n\n관리자 콘솔 → 강의 설정에서 플레이어 옵션을 조정할 수 있습니다.",
    targetType: "ALL_TENANTS",
    status: "PUBLISHED",
    sentAt: "2026-03-15T09:00:00Z",
    views: 0,
    createdAt: "2026-03-14T16:00:00Z",
    createdBy: "ops@open-knock.com",
  },
  {
    id: "ann-003",
    scope: "PLATFORM",
    subtype: "URGENT",
    title: "[긴급] SSO 로그인 간헐적 오류 조치 완료",
    content: "3월 12일 14:30 ~ 16:10 사이 SAML 기반 SSO 로그인에서 간헐적 인증 실패가 발생하였습니다.\n\n원인: Azure AD 메타데이터 엔드포인트 응답 지연\n조치: 메타데이터 캐싱 레이어 추가, 타임아웃 임계값 조정\n현재 상태: 정상 운영 중\n\n영향을 받은 테넌트: 삼성전자, 현대자동차\n사고 보고서는 이메일로 별도 발송 예정입니다.",
    targetType: "SPECIFIC_TENANTS",
    targetIds: ["t-001", "t-003"],
    status: "PUBLISHED",
    sentAt: "2026-03-12T16:30:00Z",
    views: 0,
    createdAt: "2026-03-12T16:20:00Z",
    createdBy: "ops@open-knock.com",
  },
  {
    id: "ann-004",
    scope: "PLATFORM",
    subtype: "UPDATE",
    title: "[업데이트] 관리자 콘솔 — 수강 현황 엑셀 내보내기 지원",
    content: "관리자 콘솔 수강 현황 페이지에서 엑셀(.xlsx) 내보내기를 지원합니다.\n\n• 수강자별 진행률, 점수, 이수 여부 포함\n• 필터 조건(기간, 과정, 부서) 적용 후 내보내기 가능\n• 최대 10,000건 지원",
    targetType: "ALL_TENANTS",
    status: "PUBLISHED",
    sentAt: "2026-03-05T10:00:00Z",
    views: 0,
    createdAt: "2026-03-04T17:00:00Z",
    createdBy: "ops@open-knock.com",
  },
  {
    id: "ann-005",
    scope: "PLATFORM",
    subtype: "GENERAL",
    title: "2026년 1분기 서비스 운영 리포트 발송 안내",
    content: "2026년 1분기(1~3월) 서비스 운영 리포트를 4월 초에 어드민 이메일로 발송할 예정입니다.\n\n포함 내용:\n• 테넌트별 월간 활성 사용자 추이\n• 강의 완료율 평균\n• 스토리지 사용량 현황\n• 서비스 가용성(SLA) 달성률",
    targetType: "ALL_TENANTS",
    status: "DRAFT",
    views: 0,
    createdAt: "2026-03-18T11:00:00Z",
    createdBy: "admin@open-knock.com",
  },
];
